-- MySQL Script generated by MySQL Workbench
-- Wed Feb 20 13:15:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ThuVienSach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ThuVienSach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ThuVienSach` DEFAULT CHARACTER SET utf8 ;
USE `ThuVienSach` ;

-- -----------------------------------------------------
-- Table `ThuVienSach`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThuVienSach`.`Student` (
  `student_id` CHAR(5) NOT NULL,
  `student_name` VARCHAR(30) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThuVienSach`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThuVienSach`.`Category` (
  `category_id` CHAR(5) NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`),
  CONSTRAINT `cate_bookcate`
    FOREIGN KEY (`category_id`)
    REFERENCES `ThuVienSach`.`Book_Cate` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThuVienSach`.`Book_Cate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThuVienSach`.`Book_Cate` (
  `book_id` CHAR(5) NOT NULL,
  `category_id` CHAR(5) NOT NULL,
  PRIMARY KEY (`book_id`, `category_id`),
  INDEX `bkcat_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `bkcat_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `ThuVienSach`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bkcat_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `ThuVienSach`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThuVienSach`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThuVienSach`.`Book` (
  `book_id` CHAR(5) NOT NULL,
  `book_name` VARCHAR(50) NOT NULL,
  `category_id` CHAR(5) NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `bok_cat_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `bok_cat`
    FOREIGN KEY (`category_id`)
    REFERENCES `ThuVienSach`.`Book_Cate` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ThuVienSach`.`BorrowOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ThuVienSach`.`BorrowOrder` (
  `borroworder_id` CHAR(5) NOT NULL,
  `book_id` CHAR(5) NOT NULL,
  `student_id` CHAR(5) NOT NULL,
  `borrowdate` DATE NOT NULL,
  `requiredate` DATE NOT NULL,
  `returndate` DATE NULL,
  PRIMARY KEY (`borroworder_id`),
  INDEX `br_book_idx` (`book_id` ASC) VISIBLE,
  INDEX `br_student_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `br_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `ThuVienSach`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `br_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `ThuVienSach`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
